-- MySQL Script generated by MySQL Workbench
-- 12/12/16 20:25:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`coloc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coloc` (
  `id_coloc` INT NOT NULL COMMENT '',
  `nom_coloc` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_coloc`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` (16) NOT NULL COMMENT '',
  `email` (255) NOT NULL COMMENT '',
  `password` (32) NOT NULL COMMENT '',
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`email`, `coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_user_coloc`
    FOREIGN KEY (`coloc_id_coloc`)
    REFERENCES `mydb`.`coloc` (`id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_user_coloc_idx` ON `mydb`.`user` (`coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`listecourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listecourse` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_listecourse_coloc1`
    FOREIGN KEY (`coloc_id_coloc`)
    REFERENCES `mydb`.`coloc` (`id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_listecourse_coloc1_idx` ON `mydb`.`listecourse` (`coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`itemcourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemcourses` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `quantity` DECIMAL NOT NULL COMMENT '',
  `order` INT NOT NULL COMMENT '',
  `listecourse_id` INT NOT NULL COMMENT '',
  `listecourse_coloc_id_coloc` INT NOT NULL COMMENT '',
  `date_dernier_achat` DATE NULL COMMENT '',
  PRIMARY KEY (`id`, `listecourse_id`, `listecourse_coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_itemcourses_listecourse1`
    FOREIGN KEY (`listecourse_id` , `listecourse_coloc_id_coloc`)
    REFERENCES `mydb`.`listecourse` (`id` , `coloc_id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_itemcourses_listecourse1_idx` ON `mydb`.`itemcourses` (`listecourse_id` ASC, `listecourse_coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`dépense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dépense` (
  `id` INT NOT NULL COMMENT '',
  `intitule` VARCHAR(45) NULL COMMENT '',
  `montant` FLOAT NOT NULL COMMENT '',
  `user_email` (255) NOT NULL COMMENT '',
  `user_coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `user_email`, `user_coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_dépense_user1`
    FOREIGN KEY (`user_email` , `user_coloc_id_coloc`)
    REFERENCES `mydb`.`user` (`email` , `coloc_id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dépense_user1_idx` ON `mydb`.`dépense` (`user_email` ASC, `user_coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evenement` (
  `id` INT NOT NULL COMMENT '',
  `intitule` VARCHAR(45) NULL COMMENT '',
  `commence` DATE NULL COMMENT '',
  `fini` DATE NULL COMMENT '',
  `coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_evenement_coloc1`
    FOREIGN KEY (`coloc_id_coloc`)
    REFERENCES `mydb`.`coloc` (`id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_evenement_coloc1_idx` ON `mydb`.`evenement` (`coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`photo` (
  `id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `ref_photo` VARCHAR(45) NULL COMMENT '',
  `date_prise` DATE NULL COMMENT '',
  `coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_photo_coloc1`
    FOREIGN KEY (`coloc_id_coloc`)
    REFERENCES `mydb`.`coloc` (`id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_photo_coloc1_idx` ON `mydb`.`photo` (`coloc_id_coloc` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`identification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`identification` (
  `photo_id` INT NOT NULL COMMENT '',
  `photo_coloc_id_coloc` INT NOT NULL COMMENT '',
  `user_email` (255) NOT NULL COMMENT '',
  `user_coloc_id_coloc` INT NOT NULL COMMENT '',
  PRIMARY KEY (`photo_id`, `photo_coloc_id_coloc`, `user_email`, `user_coloc_id_coloc`)  COMMENT '',
  CONSTRAINT `fk_identification_photo1`
    FOREIGN KEY (`photo_id` , `photo_coloc_id_coloc`)
    REFERENCES `mydb`.`photo` (`id` , `coloc_id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_identification_user1`
    FOREIGN KEY (`user_email` , `user_coloc_id_coloc`)
    REFERENCES `mydb`.`user` (`email` , `coloc_id_coloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_identification_user1_idx` ON `mydb`.`identification` (`user_email` ASC, `user_coloc_id_coloc` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
